name: hobi_baca
description: Aplikasi Beli dan Baca Buku PDF.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http:
  shared_preferences:
  shimmer:
  intl:
  provider:
  easy_pdf_viewer:
  cached_network_image:
  flutter_launcher_icons:
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"
  min_sdk_android: 16

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
